### ISSUE TITLE
Inconsistent Multipart type when some fields are not files

### ISSUE THREAD

**Issue by JbIPS** [fastify/fastify-multipart#162]
# 🐛 Bug Report

When sending multiple fields in the form-data, Typescript types them all as files, even if it's not the case

## To Reproduce

```js
server.post<{Body: {field1: Multipart, field2:Multipart}}>(...)
```

```
http -f :3000/mulitpart field1=foo field2@myFile.txt
```
With this call, we submit a file and a string. But due to the [Multipart type](https://github.com/fastify/fastify-multipart/blob/master/index.d.ts#L26), they're all typed the same and we can't access the `.value` property containing the string (as in this [test](https://github.com/fastify/fastify-multipart/blob/master/test/multipart-body-schema.test.js#L45)).

## Expected behavior

We could take advantage of TypeScript [conditional typing](https://www.typescriptlang.org/docs/handbook/advanced-types.html#conditional-types) to allow user to properly type its body.

```typescript
interface MultipartFile {
    filename: string;
}
interface MultipartString {
    value: string;
}
type Multipart<T = true> = T extends string ? MultipartString : MultipartFile;

const mult = {} as Multipart<string>
mult.value // OK
mult.filename // error

const multFile = {} as Multipart
multFile.value // error
multFile.filename // OK
```
[Playground to see it in action](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgLIFcA2ZgAc5RgBiwmKA3gLABQydyMpEIcAthAFzIDOYUoAcwDcNAL41QkWIhQZseAmADKfQciq16ANziZ0nHqpDCxNMAE9csrDnyEAPABVkAXmR99APlfJnEAB6QIAAm3Ib8xsgA-Gg2CoQqEQLIXHK2iiRkItQ0CAD2ILzIrDY+5KLIcGFp8WD2vEmeNCXYAHQ6eigA9F3IAPIA0s02rYxkLOzIPcjQUHlQNLkFRS3ETGUVVbHydmDD2JkQ7br6U72z8-trZKNME929g0A)

## Your Environment

- *node version*: 14
- *TypeScript version*: 4.0.2
- *fastify version*: 3.3.0
- *fastiify-multipart version*: 3.2.0
- *os*: Linux

**Comment by StarpTech** [comment]
Make sense. Feel free to create a PR.

**Comment by JbIPS** [comment]
Done! Let me know if you need anything more :smiley:

**Comment by cstrnt** [comment]
Just stumbled upon this issue while using this plugin. Any chance we could add docs for that?

**Comment by StarpTech** [comment]
Definitly. We could create a section called "Typescript usage" and link it to https://github.com/fastify/fastify-multipart/blob/master/test/index.test-d.ts

**Comment by mage1k99** [comment]
Still there is no section for typescript usage 🤔

**Comment by marcelo-agil** [comment]
Why is this issue closed? The problem persists... it took hours for me to find this result in google.
(After I tried everything, I realized it would be a problem with the plugin).
